<div class="col-sm-12">
    <?php
        $this->flashMessenger()
            ->setMessageOpenFormat('<div%s>')
            ->setMessageCloseString('<button data-dismiss="alert" class="close"><span aria-hidden="true">&times;</span></button></div>');

        echo $this->flashMessenger()->render('error', array('alert', 'alert-danger', 'alert-dismissible', 'fade in'));
        echo $this->flashMessenger()->render('info', array('alert', 'alert-info'));
        echo $this->flashMessenger()->render('success', array('alert', 'alert-success'));
        echo $this->flashMessenger()->render('warning', array('alert', 'alert-warning'));

    ?>
</div>
